# Feature/Data Engineering: encoding

In our last session, we expanded on the curriculum by looking deeper on how to apply unsupervised learning techniques such as DBScan Clustering and PCA not only for EDA and dimensionality reduction but also on how we can create new features aka feature engineering. If you're interested in reviewing feature engineering for numerical data (with examples), check out:
- notebooks/Mod4_Data_Analytics.ipynb
- notebooks/Mod6_PCA_Clustering.ipynb

In this session, we're going to explore Feature Engineering for categorical features and text-based data: preparing you not only in traditional ML but also for Generative AI such as LLMs.

Before we dive into encoding (tokenization) for LLMs, let’s revisit how we handle feature encoding for categorical data — a crucial step that parallels what LLMs later do implicitly with text.

### Table of Contents
1. [Setup and Data Loading](#1-setup-and-data-loading)
2. [Ordinal Encoding](#2-ordinal-encoding)
3. [One-hot Encoding](#3-oh-encoding)
4. [LLM Encoding](#4-llm-encoding)
5. [Feature Engineering: Tokeniser](#5-tokeniser)
6. [Summary & Statistics](#6-summary-stats)

#### Notebook Workflow

![Notebook Workflow](../images/Mod8_Feat_Engineering_flow.png)

---
## 1. Setup and Data Loading <a id='1-setup-and-data-loading'></a>

In [25]:
import pathlib

import pandas as pd
import spacy

import requests
from bs4 import BeautifulSoup

from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.pre_tokenizers import Whitespace
from tokenizers.trainers import BpeTrainer

from IPython.display import Image, HTML, display

In [2]:
# Visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

# Set visualization styles
plt.style.use('seaborn-v0_8-muted')
sns.set_palette('husl')
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

# Plot settings
FIGSIZE = (12, 6)
TITLE_FONTSIZE = 14
LABEL_FONTSIZE = 12

In [3]:
import sys
parent=pathlib.Path.cwd().parent
sys.path.insert(0,str(parent))

from helpers.visuals import show_mermaid_diagram

Let's create a simple sentence, split it into words, and capture the unique words in a dataframe

In [ ]:
sentence = "I love everything involving AI and machine learning and love the University of California, Berkeley!"

words = sentence.split()

unique_words = list(dict.fromkeys(words))

df = pd.DataFrame(words, columns=['word'])

---
## 2. Ordinal Encoding <a id='2-ordinal-encoding'></a>


IF you have categorical data WITH inherent order (e.g., small/medium/large, education levels) → Use ordinal
- Applied to categorical features (words, categories)
- Output is a single integer
- Used for features with inherent order

In [5]:
ord_encoder = OrdinalEncoder(categories=[unique_words],dtype=int)

encoded_ord = ord_encoder.fit_transform(df[['word']].astype(str))

df_ordinal = df.copy()
df_ordinal['ordinal_id'] = encoded_ord.astype(int)

df_ordinal

           word  ordinal_id
0             I           0
1          love           1
2    everything           2
3     involving           3
4            AI           4
5           and           5
6       machine           6
7      learning           7
8           and           5
9          love           1
10          the           8
11   University           9
12           of          10
13  California,          11
14    Berkeley!          12

---
## 3. One-hot Encoding <a id='3-oh-encoding'></a>

Using one-hot encoding and a dataframe, we can create and visualise the occurrence of each unique word (categorical data), now as a feature column. 
Tip: IF you have categorical data with NO inherent order (e.g., colors, countries) → Use one-hot

In [8]:
oh_encoder = OneHotEncoder(categories=[unique_words], sparse_output=False, dtype=int, handle_unknown="ignore")

encoded_oh = oh_encoder.fit_transform(df[['word']])

encoded_df = pd.DataFrame(encoded_oh, columns=[f'_{word.lower()}' for word in unique_words], index=df.index)

df_one_hot = pd.concat([df.reset_index(drop=True), encoded_df], axis=1)
df_one_hot

,word,_i,_love,_everything,_involving,_ai,_and,_machine,_learning,_the,_university,_of,"_california,",_berkeley!
0,I,1,0,0,0,0,0,0,0,0,0,0,0,0
1,love,0,1,0,0,0,0,0,0,0,0,0,0,0
2,everything,0,0,1,0,0,0,0,0,0,0,0,0,0
3,involving,0,0,0,1,0,0,0,0,0,0,0,0,0
4,AI,0,0,0,0,1,0,0,0,0,0,0,0,0
5,and,0,0,0,0,0,1,0,0,0,0,0,0,0
6,machine,0,0,0,0,0,0,1,0,0,0,0,0,0
7,learning,0,0,0,0,0,0,0,1,0,0,0,0,0
8,and,0,0,0,0,0,1,0,0,0,0,0,0,0
9,love,0,1,0,0,0,0,0,0,0,0,0,0,0
10,the,0,0,0,0,0,0,0,0,1,0,0,0,0
11,University,0,0,0,0,0,0,0,0,0,1,0,0,0
12,of,0,0,0,0,0,0,0,0,0,0,1,0,0
13,"California,",0,0,0,0,0,0,0,0,0,0,0,1,0
14,Berkeley!,0,0,0,0,0,0,0,0,0,0,0,0,1

### Advanced: From Text --> Categorical Data --> One-Hot Encoding

So far, we’ve treated words themselves as categories and encoded them directly - but in the real-world we often want to transform raw text into higher-level categorical features before encoding. 

One way to create categorical features from raw text (and then encode) is to categorise words into nouns, verbs, adjectives etc. aka part of speech (POS)

In Natural Language Processing (NLP), which we will cover later, you can do this using a library like spacy. 

*Note: when updating for all installs (pip install -r requirements.txt) to install spacy you will still need to run the command: python -m spacy download en_core_web_sm*

In [9]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 1.7 MB/s  0:00:07m0:00:0100:01m
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [10]:
categorise_text = spacy.load("en_core_web_sm")

text = categorise_text(sentence)

words = []
pos_categ = []

for token in text:
    if token.is_space or token.is_punct:
        continue
    words.append(token.text)
    pos_categ.append(token.pos_)

df_pos = pd.DataFrame({'word': words,'pos': pos_categ})

unique_pos = list(dict.fromkeys(pos_categ))

oh_encoder = OneHotEncoder(categories=[unique_pos], sparse_output=False, dtype=int, handle_unknown="ignore")

encoded_oh = oh_encoder.fit_transform(df_pos[['pos']])

encoded_df = pd.DataFrame(encoded_oh, columns=[f'_{pos.lower()}' for pos in unique_pos], index=df_pos.index)

df_pos_ohe = pd.concat([df_pos.reset_index(drop=True), encoded_df], axis=1)
df_pos_ohe

          word    pos  _pron  _verb  _propn  _cconj  _noun  _det  _adp
0            I   PRON      1      0       0       0      0     0     0
1         love   VERB      0      1       0       0      0     0     0
2   everything   PRON      1      0       0       0      0     0     0
3    involving   VERB      0      1       0       0      0     0     0
4           AI  PROPN      0      0       1       0      0     0     0
5          and  CCONJ      0      0       0       1      0     0     0
6      machine   NOUN      0      0       0       0      1     0     0
7     learning   NOUN      0      0       0       0      1     0     0
8          and  CCONJ      0      0       0       1      0     0     0
9         love   VERB      0      1       0       0      0     0     0
10         the    DET      0      0       0       0      0     1     0
11  University  PROPN      0      0       1       0      0     0     0
12          of    ADP      0      0       0       0      0     0     1
13  California  PROPN      0      0       1       0      0     0     0
14    Berkeley  PROPN      0      0       1       0      0     0     0

These encoders give numerical structure to non-numeric data. However, they rely entirely on human-defined categories. In contrast, LLMs will learn their own encoding rules.

---
## 4. LLM Encoding  <a id='4-llm-encoding'></a>

### Understanding Latent Features
Whenever you apply scaling, PCA, or clustering on numerical data, you're effectively trying to uncover hidden features that aren't visible in your existing dataset.

For example, PCA explicitly creates **latent features** (principal components) through linear combinations of our existing numerical features. In LLMs, latent features are not computed algorithmically or assumed to be linear — instead they emerge from the raw data as part of training.

In other words:
- Traditional ML: **you** *engineer* latent features explicitly → using tools like PCA or clustering
- LLMs: the **model** *discovers* latent features implicitly → through backpropagation (as you will learn when studying neural networks later)

### Understanding Implicit Features
In traditional ML, we encode text features using techniques such as ordinal encoding or one-hot encoding to transform them into a numerical format the model can ingest. With LLMs, we still need to prepare data for encoding, but we're not encoding features ourselves.

LLMs identify features implicitly within their neural layers during training, rather than explicitly during data preprocessing as we have seen with typical regression and classifier models.

Summary:
- ML Features: explicit, identified by the Data Scientist before training
- LLM Features: implicit, discovered by the Model during training

Let's visualise how these two approaches are similar and differ:

In [3]:
show_mermaid_diagram("ml_llm_data_prep_pipeline")

#### Token Encoding: unique letter combinations --> token id

Intuitively, we often see frequent letter combinations appearing together in a lot of words. For example, "ing" appears often at the end of some words, while "th" often appear together at the start. 

It's these frequently appearing character combinations in languages that form the basis of the tokenisation process - whereby we have algorithms such as **Byte Pair Encoding (BPE)** that, given a text dataset (corpus):
- identify the most frequent combinations of characters in your 'corpus' as features → **feature extraction**
- map each feature to a unique integer (token id) suitable for model training → **feature engineering**

In practise, this encoding process can be quite time-consuming and complicated (how can you guarantee the sub-string and ID matches don't change when you update your training corpus?!?!).

As a result, most LLMS use pre-trained encoders created from other models aka Tokenisers.

Nonetheless, we can learn a lot about LLMs and feature engineering by creating one ourselves in the next section:
- Want to visualise text tokenisation in OpenAI models? [Tiktokenizer ](https://tiktokenizer.vercel.app/)

---
## 5. Feature Engineering: Tokeniser <a id='5-tokeniser'></a>

Let's create our corpus by scraping text from this courses description at UC Berkeley's Executive Education Program: https://em-executive.berkeley.edu/professional-certificate-machine-learning-artificial-intelligence

In [ ]:
dataset_dir = pathlib.Path("../datasets")


url = "https://em-executive.berkeley.edu/professional-certificate-machine-learning-artificial-intelligence"

corpus_source = requests.get(url)
corpus_source.raise_for_status()
soup = BeautifulSoup(corpus_source.text, "html.parser")

In [ ]:
paragraphs = [p.get_text().strip() for p in soup.find_all("p") if p.get_text().strip()]
full_text = "\n".join(paragraphs)

### Corpus

In [29]:
corpus = dataset_dir / "corpus_full.txt"
with corpus.open("w", encoding="utf-8") as f:
    f.write(full_text)

### Tokenizer Inputs
Select the tokenizer algorithm and any pre-processing steps.

Now that our text corpus is saved, let’s train our own BPE-based tokenizer. This is the same type of process used by models like GPT, except on a massive scale.

In [ ]:
tokenizer = Tokenizer(BPE())
tokenizer.pre_tokenizer = Whitespace()

In [ ]:
trainer = BpeTrainer(special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"],vocab_size=2000)

tokenizer.train(files=[str(corpus)], trainer=trainer)

### Tokeniser Vocab (aka Dictionary)
That's it. We used BPE to create a "vocabulary" of every frequent character combination in our corpus, along with a unique token id.

Below is a sample of the tokens our tokenizer learned — these represent frequent subword units discovered from the training corpus.

In [ ]:
vocab = tokenizer.get_vocab()

print("Random sample of the tokens and their IDs our tokenizer learned:\n")
for token, idx in list(vocab.items())[:5]:
    print(f"{idx}: {token}")

Random sample of the tokens and their IDs our tokenizer learned:

991: Califor
102: the
1128: versity
1872: expect
1870: excl

---
## 6. Summary & Statistics <a id='6-summary-stats'></a>

Let’s now merge our outputs — one-hot, ordinal, and BPE — into a single table to visually compare how traditional and LLM encodings handle our original sentence. For ease, lets' bring the sentence back down here.

In [22]:
sentence = "I love everything involving AI and machine learning and love the University of California, Berkeley!"

words = sentence.split()

token_ids = []
for word in words:
    encoded = tokenizer.encode(word)
    token_ids.append(encoded.ids)

df_bpe = pd.DataFrame({"word": words,"token_id": token_ids})

In [23]:
df_ordinal["idx"] = df_ordinal.index
df_pos_ohe["idx"] = df_pos_ohe.index
df_bpe["idx"]      = df_bpe.index

df_encode = (df_bpe.merge(df_pos_ohe, on=["idx", "word"]).drop(columns="pos"))
df_encode = (df_encode.merge(df_ordinal, on=["idx", "word"]).drop(columns="idx"))
df_encode

,word,token_id,_pron,_verb,_propn,_cconj,_noun,_det,_adp,ordinal_id
0,I,[39],1,0,0,0,0,0,0,0
1,love,"[136, 121]",0,1,0,0,0,0,0,1
2,everything,"[587, 80, 1731]",1,0,0,0,0,0,0,2
3,involving,"[88, 77, 1846]",0,1,0,0,0,0,0,3
4,AI,[151],0,0,1,0,0,0,0,4
5,and,[100],0,0,0,1,0,0,0,5
6,machine,[918],0,0,0,0,1,0,0,6
7,learning,[175],0,0,0,0,1,0,0,7
8,and,[100],0,0,0,1,0,0,0,5
9,love,"[136, 121]",0,1,0,0,0,0,0,1
10,the,[102],0,0,0,0,0,1,0,8
11,University,[1386],0,0,1,0,0,0,0,9
12,of,[113],0,0,0,0,0,0,1,10

### Tokens > words
In our sentence, despite the word "involving" (idx: 3) never appearing in our Corpus it is nonetheless tokenised with IDs [83, 76, 722]. 

This is because "involving" was tokenised into "inv", "olv" and "ing":
- "inv" appeared 8 times in the corpus from the word "invite" --> encoded with token id: 83
- "olv" appeared 6 times in the corpus, from words such as "solve" and "evolve" --> encoded with token id: 76
- "ing" appeared 152 times in the corpus, from lots of words! --> encoded with token id 722